import { randomFrom } from "./random";

const FJUWORDZ_DATABASE = {
  actions: [
    "Leading", "Managing", "Directing", "Guiding", "Overseeing", "Supervising",
    "Coordinating", "Orchestrating", "Facilitating", "Administering", "Governing",
    "Steering", "Piloting", "Helming", "Captaining", "Commanding", "Spearheading",
    "Growing", "Developing", "Expanding", "Scaling", "Building", "Establishing",
    "Creating", "Forming", "Constructing", "Designing", "Architecting", "Engineering",
    "Cultivating", "Nurturing", "Fostering", "Advancing", "Progressing", "Evolving",
    "Improving", "Enhancing", "Optimizing", "Refining", "Perfecting", "Polishing",
    "Streamlining", "Simplifying", "Modernizing", "Upgrading", "Updating", "Revitalizing",
    "Strengthening", "Reinforcing", "Fortifying", "Boosting", "Elevating", "Amplifying",
    "Transforming", "Revolutionizing", "Reimagining", "Reinventing", "Reshaping",
    "Redefining", "Restructuring", "Reorganizing", "Reforming", "Renewing", "Refreshing",
    "Pivoting", "Transitioning", "Shifting", "Adapting", "Adjusting", "Modifying",
    "Achieving", "Accomplishing", "Attaining", "Reaching", "Realizing", "Fulfilling",
    "Delivering", "Executing", "Implementing", "Completing", "Finishing", "Concluding",
    "Succeeding", "Excelling", "Thriving", "Flourishing", "Prospering",
    "Discovering", "Exploring", "Investigating", "Researching", "Analyzing", "Examining",
    "Innovating", "Pioneering", "Trailblazing", "Inventing", "Originating", "Initiating",
    "Uncovering", "Revealing", "Identifying", "Recognizing", "Detecting", "Finding",
    "Integrating", "Connecting", "Linking", "Bridging", "Unifying", "Consolidating",
    "Merging", "Combining", "Blending", "Harmonizing", "Synchronizing", "Aligning",
    "Partnering", "Collaborating", "Cooperating", "Teaming", "Joining", "Associating",
    "Communicating", "Engaging", "Interacting", "Networking", "Presenting", "Sharing",
    "Discussing", "Dialoguing", "Conversing", "Consulting", "Advising", "Counseling",
    "Mentoring", "Coaching", "Teaching", "Training", "Educating", "Instructing",
    "Planning", "Strategizing", "Forecasting", "Projecting", "Anticipating", "Preparing",
    "Organizing", "Arranging", "Structuring", "Systematizing", "Scheduling", "Prioritizing",
    "Mapping", "Charting", "Outlining", "Drafting", "Formulating", "Devising",
    "Empowering", "Enabling", "Equipping", "Arming", "Preparing", "Readying",
    "Supporting", "Assisting", "Helping", "Aiding", "Backing", "Championing",
    "Advocating", "Promoting", "Endorsing", "Sponsoring", "Encouraging", "Inspiring",
    "Evaluating", "Assessing", "Measuring", "Quantifying", "Benchmarking", "Comparing",
    "Reviewing", "Auditing", "Inspecting", "Monitoring", "Tracking", "Observing",
    "Studying", "Surveying", "Probing", "Testing", "Validating", "Verifying",
    "Maximizing", "Leveraging", "Capitalizing", "Exploiting", "Utilizing", "Harnessing",
    "Mobilizing", "Activating", "Energizing", "Galvanizing", "Catalyzing", "Igniting",
    "Propelling", "Driving", "Pushing", "Accelerating", "Expediting", "Fast-tracking"
  ],
  qualities: [
    "Excellence", "Performance", "Quality", "Standards", "Benchmarks", "Metrics",
    "Achievements", "Accomplishments", "Results", "Outcomes", "Deliverables", "Outputs",
    "Success", "Victory", "Triumph", "Mastery", "Expertise", "Proficiency",
    "Growth", "Development", "Progress", "Advancement", "Evolution", "Maturation",
    "Expansion", "Scaling", "Acceleration", "Momentum", "Velocity", "Trajectory",
    "Improvement", "Enhancement", "Optimization", "Refinement", "Elevation", "Uplift",
    "Innovation", "Creativity", "Ingenuity", "Originality", "Inventiveness", "Imagination",
    "Vision", "Foresight", "Insight", "Wisdom", "Intelligence", "Brilliance",
    "Inspiration", "Motivation", "Aspiration", "Ambition", "Drive", "Determination",
    "Efficiency", "Productivity", "Effectiveness", "Profitability", "Sustainability", "Viability",
    "Reliability", "Dependability", "Consistency", "Stability", "Durability", "Longevity",
    "Agility", "Flexibility", "Adaptability", "Versatility", "Scalability", "Portability",
    "Leadership", "Influence", "Impact", "Authority", "Credibility", "Reputation",
    "Presence", "Charisma", "Gravitas", "Stature", "Standing", "Recognition",
    "Distinction", "Prominence", "Eminence", "Prestige", "Honor", "Respect",
    "Collaboration", "Cooperation", "Partnership", "Alliance", "Coalition", "Federation",
    "Unity", "Harmony", "Synergy", "Cohesion", "Integration", "Alignment",
    "Teamwork", "Camaraderie", "Fellowship", "Brotherhood", "Solidarity", "Togetherness",
    "Strategy", "Planning", "Preparation", "Organization", "Structure", "Framework",
    "Architecture", "Blueprint", "Roadmap", "Pathway", "Direction", "Course",
    "Approach", "Methodology", "Process", "Procedure", "Protocol", "System",
    "Value", "Worth", "Merit", "Significance", "Importance", "Relevance",
    "Meaning", "Purpose", "Mission", "Vision", "Goals", "Objectives",
    "Targets", "Milestones", "Benchmarks", "Standards", "Criteria", "Specifications",
    "Trust", "Integrity", "Honesty", "Transparency", "Authenticity", "Genuineness",
    "Ethics", "Morality", "Principles", "Values", "Beliefs", "Convictions",
    "Accountability", "Responsibility", "Ownership", "Commitment", "Dedication", "Devotion",
    "Resilience", "Strength", "Fortitude", "Tenacity", "Persistence", "Perseverance",
    "Endurance", "Stamina", "Vigor", "Vitality", "Energy", "Power",
    "Force", "Might", "Capability", "Capacity", "Potential", "Possibility",
    "Knowledge", "Learning", "Education", "Training", "Development", "Growth",
    "Understanding", "Comprehension", "Awareness", "Consciousness", "Mindfulness", "Attention",
    "Focus", "Concentration", "Clarity", "Precision", "Accuracy", "Exactness"
  ],
  domains: [
    "Leadership Development", "Executive Management", "Strategic Leadership", "Team Leadership",
    "Organizational Leadership", "Thought Leadership", "Servant Leadership", "Transformational Leadership",
    "Change Leadership", "Innovation Leadership", "Digital Leadership", "Global Leadership",
    "Strategic Planning", "Business Strategy", "Corporate Strategy", "Growth Strategy",
    "Market Strategy", "Competitive Strategy", "Innovation Strategy", "Digital Strategy",
    "Transformation Strategy", "Expansion Strategy", "Partnership Strategy", "Alliance Strategy",
    "Business Operations", "Operational Excellence", "Process Improvement", "Process Optimization",
    "Workflow Management", "Quality Management", "Performance Management", "Resource Management",
    "Project Management", "Program Management", "Portfolio Management", "Asset Management",
    "Talent Management", "Talent Development", "Talent Acquisition", "Workforce Planning",
    "Employee Engagement", "Employee Development", "Career Development", "Professional Development",
    "Leadership Training", "Executive Coaching", "Team Building", "Culture Development",
    "Innovation Management", "Technology Innovation", "Digital Innovation", "Product Innovation",
    "Service Innovation", "Process Innovation", "Business Model Innovation", "Open Innovation",
    "Disruptive Innovation", "Sustainable Innovation", "Social Innovation", "Collaborative Innovation",
    "Brand Strategy", "Brand Development", "Brand Management", "Brand Building",
    "Marketing Strategy", "Content Strategy", "Digital Marketing", "Relationship Marketing",
    "Customer Marketing", "Product Marketing", "Corporate Marketing", "Strategic Marketing",
    "Customer Experience", "Customer Success", "Customer Engagement", "Customer Relations",
    "Client Management", "Client Development", "Client Success", "Client Partnership",
    "Stakeholder Management", "Stakeholder Engagement", "Partner Relations", "Vendor Relations",
    "Business Intelligence", "Data Analytics", "Advanced Analytics", "Predictive Analytics",
    "Market Intelligence", "Competitive Intelligence", "Strategic Intelligence", "Operational Intelligence",
    "Performance Analytics", "Customer Analytics", "Workforce Analytics", "Financial Analytics",
    "Digital Transformation", "Business Transformation", "Organizational Transformation", "Cultural Transformation",
    "Change Management", "Transition Management", "Transformation Management", "Evolution Management",
    "Modernization Programs", "Renewal Initiatives", "Revitalization Projects", "Restructuring Efforts",
    "Business Development", "Market Development", "Product Development", "Service Development",
    "Capability Development", "Competency Development", "Skill Development", "Knowledge Development",
    "Partnership Development", "Ecosystem Development", "Community Development", "Network Development",
    "Management Consulting", "Strategy Consulting", "Operations Consulting", "Technology Consulting",
    "Business Advisory", "Strategic Advisory", "Executive Advisory", "Leadership Advisory",
    "Transformation Advisory", "Innovation Advisory", "Growth Advisory", "Performance Advisory",
    "Research Programs", "Development Initiatives", "Innovation Labs", "Excellence Centers",
    "Knowledge Centers", "Learning Academies", "Leadership Institutes", "Strategy Forums",
    "Think Tanks", "Innovation Hubs", "Collaboration Spaces", "Co-Creation Labs"
  ],
  outcomes: [
    "High-Performing Teams", "Engaged Workforce", "Empowered Employees", "Skilled Professionals",
    "Strong Leadership", "Effective Management", "Aligned Organization", "Cohesive Culture",
    "Collaborative Environment", "Innovative Mindset", "Growth Orientation", "Excellence Focus",
    "Measurable Results", "Tangible Outcomes", "Sustainable Performance", "Consistent Excellence",
    "Operational Efficiency", "Process Excellence", "Service Quality", "Product Excellence",
    "Market Leadership", "Industry Recognition", "Competitive Advantage", "Strategic Position",
    "Sustainable Growth", "Accelerated Expansion", "Market Penetration", "Geographic Reach",
    "Customer Base Growth", "Revenue Enhancement", "Margin Improvement", "Portfolio Expansion",
    "Capability Enhancement", "Competency Building", "Skill Advancement", "Knowledge Growth",
    "Digital Capabilities", "Innovation Pipeline", "Technology Adoption", "Modern Infrastructure",
    "Transformed Operations", "Evolved Processes", "Updated Systems", "Enhanced Platforms",
    "New Opportunities", "Fresh Perspectives", "Novel Approaches", "Creative Solutions",
    "Strong Partnerships", "Strategic Alliances", "Valuable Networks", "Trusted Relationships",
    "Customer Loyalty", "Client Retention", "Stakeholder Trust", "Partner Confidence",
    "Community Connection", "Industry Standing", "Market Presence", "Brand Recognition",
    "Clear Direction", "Strategic Clarity", "Defined Roadmap", "Actionable Plans",
    "Aligned Priorities", "Focused Objectives", "Measurable Goals", "Achievable Targets",
    "Long-Term Vision", "Future Readiness", "Change Preparedness", "Transformation Success",
    "Positive Culture", "Shared Values", "Common Purpose", "Unified Vision",
    "Ethical Standards", "Professional Conduct", "Responsible Practices", "Sustainable Operations",
    "Inclusive Environment", "Diverse Workforce", "Equitable Opportunities", "Fair Treatment",
    "Organizational Learning", "Knowledge Sharing", "Best Practices", "Lessons Learned",
    "Continuous Improvement", "Ongoing Development", "Perpetual Growth", "Lifelong Learning",
    "Skill Mastery", "Competency Excellence", "Expertise Development", "Capability Maturity",
    "Streamlined Processes", "Optimized Workflows", "Efficient Operations", "Productive Teams",
    "Resource Optimization", "Cost Effectiveness", "Time Efficiency", "Energy Conservation",
    "Waste Reduction", "Quality Improvement", "Error Minimization", "Challenge Navigation",
    "Customer Satisfaction", "Client Success", "User Experience", "Service Excellence",
    "Market Position", "Competitive Standing", "Industry Leadership", "Sector Dominance",
    "Brand Equity", "Reputation Enhancement", "Trust Building", "Credibility Establishment"
  ],
  modifiers: [
    "Advanced", "Premium", "Superior", "Elite", "World-Class", "Best-in-Class",
    "Top-Tier", "High-Quality", "First-Rate", "Exceptional", "Outstanding", "Remarkable",
    "Distinguished", "Prestigious", "Renowned", "Acclaimed", "Celebrated", "Honored",
    "Innovative", "Creative", "Original", "Novel", "Fresh", "New",
    "Modern", "Contemporary", "Current", "Latest", "Recent", "Updated",
    "Cutting-Edge", "Leading-Edge", "State-of-the-Art", "Next-Generation", "Future-Ready", "Forward-Looking",
    "Strategic", "Tactical", "Operational", "Functional", "Structural", "Systematic",
    "Methodical", "Organized", "Planned", "Deliberate", "Intentional", "Purposeful",
    "Focused", "Targeted", "Directed", "Guided", "Oriented", "Aligned",
    "Comprehensive", "Complete", "Full", "Total", "Entire", "Whole",
    "Thorough", "Exhaustive", "Extensive", "Broad", "Wide", "Expansive",
    "All-Encompassing", "All-Inclusive", "End-to-End", "Full-Spectrum", "Multi-Faceted", "Multi-Dimensional",
    "Integrated", "Unified", "Consolidated", "Combined", "Merged", "Blended",
    "Harmonized", "Synchronized", "Coordinated", "Aligned", "Connected", "Linked",
    "Holistic", "Systemic", "Organic", "Natural", "Seamless", "Smooth",
    "Efficient", "Effective", "Productive", "Profitable", "Successful", "Thriving",
    "Optimized", "Streamlined", "Simplified", "Refined", "Polished", "Perfected",
    "Enhanced", "Improved", "Upgraded", "Elevated", "Advanced", "Developed",
    "Sustainable", "Durable", "Lasting", "Enduring", "Permanent", "Stable",
    "Reliable", "Dependable", "Consistent", "Steady", "Solid", "Strong",
    "Resilient", "Robust", "Tough", "Hardy", "Rugged", "Sturdy",
    "Flexible", "Adaptable", "Versatile", "Agile", "Dynamic", "Responsive",
    "Scalable", "Expandable", "Extensible", "Modular", "Configurable", "Customizable",
    "Adjustable", "Variable", "Changeable", "Modifiable", "Transformable", "Convertible",
    "Collaborative", "Cooperative", "Participative", "Inclusive", "Engaging", "Interactive",
    "Shared", "Joint", "Mutual", "Reciprocal", "Collective", "Communal",
    "Team-Based", "Group-Oriented", "Community-Focused", "Partner-Driven", "Alliance-Based", "Network-Centric",
    "Data-Driven", "Evidence-Based", "Research-Backed", "Fact-Based", "Insight-Led", "Analytics-Powered",
    "Measured", "Quantified", "Validated", "Verified", "Tested", "Proven",
    "Documented", "Recorded", "Tracked", "Monitored", "Observed", "Analyzed",
    "Customer-Centric", "Client-Focused", "User-Oriented", "People-First", "Human-Centered", "Value-Driven",
    "Results-Oriented", "Outcome-Focused", "Goal-Directed", "Mission-Driven", "Purpose-Led", "Vision-Guided",
    "Performance-Based", "Merit-Based", "Quality-Focused", "Excellence-Driven", "Standards-Based", "Benchmark-Led"
  ],
  topics: [
    "Programs", "Initiatives", "Projects", "Campaigns", "Endeavors", "Undertakings",
    "Ventures", "Enterprises", "Operations", "Activities", "Actions", "Efforts",
    "Movements", "Drives", "Pushes", "Thrusts", "Launches", "Rollouts",
    "Frameworks", "Models", "Templates", "Blueprints", "Designs", "Architectures",
    "Structures", "Systems", "Platforms", "Foundations", "Bases", "Groundworks",
    "Scaffolds", "Skeletons", "Outlines", "Schemas", "Patterns", "Formats",
    "Methods", "Approaches", "Techniques", "Tactics", "Strategies", "Methodologies",
    "Procedures", "Processes", "Protocols", "Practices", "Routines", "Habits",
    "Ways", "Means", "Modes", "Manners", "Styles", "Forms",
    "Solutions", "Services", "Products", "Deliverables", "Outputs",
    "Results", "Outcomes", "Benefits", "Advantages", "Gains", "Returns",
    "Rewards", "Yields", "Dividends", "Profits", "Earnings", "Proceeds",
    "Tools", "Resources", "Assets", "Instruments", "Devices", "Mechanisms",
    "Equipment", "Apparatus", "Gear", "Kit", "Supplies", "Materials",
    "Components", "Elements", "Parts", "Pieces", "Segments", "Sections",
    "Skills", "Capabilities", "Competencies", "Abilities", "Talents", "Gifts",
    "Strengths", "Powers", "Faculties", "Aptitudes", "Proficiencies", "Expertises",
    "Masteries", "Specialties", "Specializations", "Concentrations", "Focuses", "Emphases",
    "Knowledge", "Insights", "Wisdom", "Understanding", "Comprehension", "Awareness",
    "Intelligence", "Information", "Data", "Facts", "Findings", "Discoveries",
    "Revelations", "Learnings", "Lessons", "Teachings", "Instructions", "Guidance",
    "Standards", "Principles", "Guidelines", "Rules", "Regulations", "Policies",
    "Norms", "Conventions", "Customs", "Traditions", "Practices", "Protocols",
    "Codes", "Ethics", "Values", "Beliefs", "Aspirations",
    "Relationships", "Networks", "Connections", "Links", "Ties", "Bonds",
    "Partnerships", "Alliances", "Coalitions", "Federations", "Associations", "Unions",
    "Collaborations", "Cooperations", "Teamworks", "Synergies", "Harmonies", "Unities",
    "Goals", "Objectives", "Targets", "Aims", "Purposes", "Intentions",
    "Missions", "Visions", "Dreams", "Aspirations", "Ambitions", "Desires",
    "Plans", "Agendas", "Schedules", "Timelines", "Roadmaps", "Pathways",
    "Workshops", "Seminars", "Conferences", "Summits", "Forums", "Symposiums",
    "Conventions", "Congresses", "Assemblies", "Meetings", "Sessions", "Gatherings",
    "Retreats", "Bootcamps", "Intensives", "Masterclasses", "Clinics", "Labs"
  ],
  connectors: [
    "for", "through", "via", "with", "using", "leveraging",
    "toward", "towards", "into", "within", "across", "throughout",
    "among", "between", "beyond", "above", "over", "around"
  ],
  phrases: [
    "in the Modern Era", "for Tomorrow's Challenges", "in Today's Environment",
    "for Sustainable Success", "in a Changing World", "for Long-Term Growth",
    "in the Digital Age", "for Future Generations", "in Competitive Markets",
    "for Organizational Excellence", "in Dynamic Industries", "for Strategic Advantage",
    "in Complex Environments", "for Measurable Impact", "in Evolving Landscapes",
    "for Continuous Improvement", "in Global Markets", "for Lasting Results",
    "in Transforming Industries", "for Peak Performance", "in Growing Organizations",
    "for Maximum Effectiveness", "in Leading Companies", "for Optimal Outcomes"
  ]
};

const TEMPLATES_WITH_DASH = [
  "{domain} - {action} {quality}",
  "{modifier} {domain} - {action} {outcome}",
  "Leading {domain} - Preparing {outcome}",
  "{domain} - Building {outcome}",
  "{modifier} {topic} - {action} {quality}",
  "{domain} - {action} {outcome}",
  "Transformation {topic} - Tracking {outcome}",
  "{modifier} {topic} - Unlocking {outcome}",
  "{domain} - Gaining {outcome}",
  "{modifier} {domain} - Expanding {outcome}",
  "{domain} - {action} {quality}",
  "Enterprise {domain} - {action} {outcome}",
  "{modifier} {topic} - Delivering {outcome}",
  "{domain} - Creating {outcome}",
  "Business {domain} - Achieving {outcome}",
  "{modifier} {topic} - {action} {quality}",
  "{domain} - Enabling {outcome}",
  "Corporate {domain} - Fostering {quality}",
  "{modifier} {topic} - Streamlining {outcome}",
  "{domain} - Maximizing {quality}",
  "{modifier} {domain} - Pioneering {outcome}",
  "{domain} - Cultivating {quality}",
  "Global {domain} - {action} {outcome}",
  "{modifier} {topic} - Championing {quality}",
  "{domain} - Orchestrating {outcome}",
  "Strategic {domain} - {action} {quality}",
  "{modifier} {topic} - Navigating {outcome}",
  "{domain} - Spearheading {quality}",
  "Executive {domain} - {action} {outcome}",
  "{modifier} {topic} - Catalyzing {quality}"
];

const TEMPLATES_NO_DASH = [
  "Aligning {domain} {connector} {modifier} {quality}",
  "New {modifier} {topic} Ensuring {outcome}",
  "{action} {quality} Through {modifier} {topic}",
  "Building {outcome} with {modifier} {domain}",
  "{modifier} {domain} {connector} {outcome}",
  "Achieving {quality} in {domain}",
  "{action} {outcome} Through {domain}",
  "Implementing {modifier} {topic} {connector} {quality}",
  "Creating {outcome} with {domain}",
  "{modifier} Approaches to {domain}",
  "Establishing {quality} Through {domain}",
  "Developing {modifier} {topic} {connector} {outcome}",
  "{action} {quality} with {modifier} {topic}",
  "Transforming {domain} {connector} {outcome}",
  "Enhancing {quality} Through {modifier} {topic}",
  "Leveraging {domain} {connector} {outcome}",
  "Optimizing {domain} to Achieve {quality}",
  "Empowering Teams Through {modifier} {domain}",
  "Accelerating {outcome} with {domain}",
  "Cultivating {quality} in {modifier} {topic}",
  "Pioneering {outcome} Through {domain}",
  "Strengthening {quality} with {modifier} {topic}",
  "Advancing {domain} {connector} {outcome}",
  "Revolutionizing {domain} Through {modifier} {topic}",
  "Mastering {quality} in {domain}",
  "Elevating {outcome} with {modifier} {topic}",
  "Fostering {quality} Through {domain}",
  "Scaling {outcome} with {modifier} {domain}",
  "Driving {quality} in {domain} {phrase}",
  "Building {outcome} {phrase}"
];

const TEMPLATES_PHRASES = [
  "{modifier} {domain} {phrase}",
  "{action} {quality} {phrase}",
  "{domain} Strategies {phrase}",
  "Building {outcome} {phrase}",
  "{modifier} {topic} {phrase}",
  "Achieving {quality} {phrase}",
  "{domain} Excellence {phrase}",
  "Creating {outcome} {phrase}",
  "{modifier} Approaches {phrase}",
  "Developing {quality} {phrase}"
];

export function generateFjuwordzSubject(): string {
  const style = randomFrom(["dash", "no_dash", "phrase"]);
  const template =
    style === "dash"
      ? randomFrom(TEMPLATES_WITH_DASH)
      : style === "no_dash"
      ? randomFrom(TEMPLATES_NO_DASH)
      : randomFrom(TEMPLATES_PHRASES);

  return template
    .replace(/{domain}/g, randomFrom(FJUWORDZ_DATABASE.domains))
    .replace(/{action}/g, randomFrom(FJUWORDZ_DATABASE.actions))
    .replace(/{quality}/g, randomFrom(FJUWORDZ_DATABASE.qualities))
    .replace(/{outcome}/g, randomFrom(FJUWORDZ_DATABASE.outcomes))
    .replace(/{modifier}/g, randomFrom(FJUWORDZ_DATABASE.modifiers))
    .replace(/{topic}/g, randomFrom(FJUWORDZ_DATABASE.topics))
    .replace(/{connector}/g, randomFrom(FJUWORDZ_DATABASE.connectors))
    .replace(/{phrase}/g, randomFrom(FJUWORDZ_DATABASE.phrases));
}
